name: Build Site

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: pip & wheel
        run: pip install pip==23.3.1 wheel==0.38.0

      - name: Install GPU requirements.
        run: pip install -r requirements-gpu.txt

      - name: Install DEDO.
        run: pip install -e third_party/dedo

      - name: Install DP3.
        run: pip install -e third_party/3D-Diffusion-Policy/3D-Diffusion-Policy

      - name: Install Dependencies
        run: pip install -e ".[build_docs]"

      - name: Build mkdocs site
        working-directory: docs
        run: mkdocs build

      - name: Upload the built site.
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: site
          path: docs/site/
